### ISSUE TITLE
Cookie access rights

### ISSUE THREAD

**Issue by robertbakker** [gtm-templates-simo-ahava/advanced-universal-analytics#1]
Hi,

I encountered a minor issue. The cookie access rights are limited to the values '_ga' and '_gaexp'. When rewriting the cookie to a different name the script has no access.

Cheers!

**Comment by sahava** [comment]
Unfortunately there's not much I can do about this. For now, the cookies a template can set must be enumerated in the permissions - it's not possible to wildcard it.
